[package]
name = "joainas-pos"
version = "1.4.0"
description = "Joainas Supermarket & Coldstore POS System"
authors = ["Dronebug Technologies & Services"]
edition = "2021"
rust-version = "1.77"

[lib]
name = "joainas_pos_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-sql = { version = "2", features = ["sqlite"] }
tauri-plugin-shell = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
windows = { version = "0.58", features = [
  "Win32_Foundation",
  "Win32_Graphics_Printing",
  "Win32_Graphics_Gdi",
  "Win32_System_Threading",
] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
